/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UploadImport } from './routes/upload'
import { Route as R404PageImport } from './routes/404Page'
import { Route as IndexImport } from './routes/index'
import { Route as MenuLacklackImport } from './routes/menu/lacklack'
import { Route as MenuIntroduceImport } from './routes/menu/introduce'
import { Route as MenuCongestionImport } from './routes/menu/congestion'
import { Route as MenuDateImport } from './routes/menu/$date'

// Create/Update Routes

const UploadRoute = UploadImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRoute,
} as any)

const R404PageRoute = R404PageImport.update({
  id: '/404Page',
  path: '/404Page',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MenuLacklackRoute = MenuLacklackImport.update({
  id: '/menu/lacklack',
  path: '/menu/lacklack',
  getParentRoute: () => rootRoute,
} as any)

const MenuIntroduceRoute = MenuIntroduceImport.update({
  id: '/menu/introduce',
  path: '/menu/introduce',
  getParentRoute: () => rootRoute,
} as any)

const MenuCongestionRoute = MenuCongestionImport.update({
  id: '/menu/congestion',
  path: '/menu/congestion',
  getParentRoute: () => rootRoute,
} as any)

const MenuDateRoute = MenuDateImport.update({
  id: '/menu/$date',
  path: '/menu/$date',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/404Page': {
      id: '/404Page'
      path: '/404Page'
      fullPath: '/404Page'
      preLoaderRoute: typeof R404PageImport
      parentRoute: typeof rootRoute
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadImport
      parentRoute: typeof rootRoute
    }
    '/menu/$date': {
      id: '/menu/$date'
      path: '/menu/$date'
      fullPath: '/menu/$date'
      preLoaderRoute: typeof MenuDateImport
      parentRoute: typeof rootRoute
    }
    '/menu/congestion': {
      id: '/menu/congestion'
      path: '/menu/congestion'
      fullPath: '/menu/congestion'
      preLoaderRoute: typeof MenuCongestionImport
      parentRoute: typeof rootRoute
    }
    '/menu/introduce': {
      id: '/menu/introduce'
      path: '/menu/introduce'
      fullPath: '/menu/introduce'
      preLoaderRoute: typeof MenuIntroduceImport
      parentRoute: typeof rootRoute
    }
    '/menu/lacklack': {
      id: '/menu/lacklack'
      path: '/menu/lacklack'
      fullPath: '/menu/lacklack'
      preLoaderRoute: typeof MenuLacklackImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404Page': typeof R404PageRoute
  '/upload': typeof UploadRoute
  '/menu/$date': typeof MenuDateRoute
  '/menu/congestion': typeof MenuCongestionRoute
  '/menu/introduce': typeof MenuIntroduceRoute
  '/menu/lacklack': typeof MenuLacklackRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404Page': typeof R404PageRoute
  '/upload': typeof UploadRoute
  '/menu/$date': typeof MenuDateRoute
  '/menu/congestion': typeof MenuCongestionRoute
  '/menu/introduce': typeof MenuIntroduceRoute
  '/menu/lacklack': typeof MenuLacklackRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/404Page': typeof R404PageRoute
  '/upload': typeof UploadRoute
  '/menu/$date': typeof MenuDateRoute
  '/menu/congestion': typeof MenuCongestionRoute
  '/menu/introduce': typeof MenuIntroduceRoute
  '/menu/lacklack': typeof MenuLacklackRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404Page'
    | '/upload'
    | '/menu/$date'
    | '/menu/congestion'
    | '/menu/introduce'
    | '/menu/lacklack'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404Page'
    | '/upload'
    | '/menu/$date'
    | '/menu/congestion'
    | '/menu/introduce'
    | '/menu/lacklack'
  id:
    | '__root__'
    | '/'
    | '/404Page'
    | '/upload'
    | '/menu/$date'
    | '/menu/congestion'
    | '/menu/introduce'
    | '/menu/lacklack'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404PageRoute: typeof R404PageRoute
  UploadRoute: typeof UploadRoute
  MenuDateRoute: typeof MenuDateRoute
  MenuCongestionRoute: typeof MenuCongestionRoute
  MenuIntroduceRoute: typeof MenuIntroduceRoute
  MenuLacklackRoute: typeof MenuLacklackRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404PageRoute: R404PageRoute,
  UploadRoute: UploadRoute,
  MenuDateRoute: MenuDateRoute,
  MenuCongestionRoute: MenuCongestionRoute,
  MenuIntroduceRoute: MenuIntroduceRoute,
  MenuLacklackRoute: MenuLacklackRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/404Page",
        "/upload",
        "/menu/$date",
        "/menu/congestion",
        "/menu/introduce",
        "/menu/lacklack"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/404Page": {
      "filePath": "404Page.tsx"
    },
    "/upload": {
      "filePath": "upload.tsx"
    },
    "/menu/$date": {
      "filePath": "menu/$date.tsx"
    },
    "/menu/congestion": {
      "filePath": "menu/congestion.tsx"
    },
    "/menu/introduce": {
      "filePath": "menu/introduce.tsx"
    },
    "/menu/lacklack": {
      "filePath": "menu/lacklack.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
